import { FiEdit, FiTrash2, FiEye, FiPlus, FiSearch, FiX, FiUserX, FiRefreshCw, FiLogOut, FiPlay, FiPause, FiSquare, FiChevronDown, FiChevronUp, FiChevronLeft, FiChevronRight, FiDownload, FiUpload, FiFile, FiBell, FiHome, FiUsers, FiSettings, FiGrid, FiCalendar, FiClock, FiAlertCircle, FiCheckCircle, FiInfo, FiStar, FiHeart, FiShare2, FiMoreHorizontal, FiArrowUp, FiArrowDown, FiArrowLeft, FiArrowRight, FiExternalLink, FiLink, FiMail, FiPhone, FiMapPin, FiUser, FiUserPlus, FiUserCheck, FiUserMinus } from "react-icons/fi";

import { HiOutlineHome, HiOutlineCube, HiOutlineFolderOpen, HiOutlineChartBar, HiOutlineLightBulb, HiOutlineClipboardList, HiOutlineCollection, HiOutlineAcademicCap, HiOutlineOfficeBuilding, HiOutlineShieldCheck, HiOutlineAdjustments, HiOutlineAnnotation, HiOutlineExclamation, HiOutlineFlag, HiOutlineGlobe, HiOutlineHeart, HiOutlineInbox, HiOutlineLibrary, HiOutlineLocationMarker, HiOutlineLockClosed, HiOutlineLogout, HiOutlineMenu, HiOutlineMoon, HiOutlinePencil, HiOutlinePhotograph, HiOutlinePlus, HiOutlineRefresh, HiOutlineSearch, HiOutlineSun, HiOutlineSwitchHorizontal, HiOutlineTag, HiOutlineTicket, HiOutlineTrash, HiOutlineTrendingUp, HiOutlineTrendingDown, HiOutlineUser, HiOutlineUserAdd, HiOutlineUserGroup, HiOutlineUserRemove, HiOutlineViewGrid, HiOutlineViewList, HiOutlineX, HiOutlineZoomIn, HiOutlineZoomOut, HiOutlineCog, HiOutlineDocumentReport, HiOutlineDocumentText, HiOutlineExclamationCircle, HiOutlineCheckCircle, HiOutlineInformationCircle, HiOutlineClock, HiOutlineCalendar, HiOutlineChartSquareBar, HiOutlineCode, HiOutlineColorSwatch, HiOutlineDatabase, HiOutlineDesktopComputer, HiOutlineDeviceMobile, HiOutlineDotsHorizontal, HiOutlineDotsVertical, HiOutlineDownload, HiOutlineDuplicate, HiOutlineUpload, HiOutlineExternalLink, HiOutlineEye, HiOutlineEyeOff, HiOutlineFilter, HiOutlineFolder, HiOutlineGift, HiOutlineHashtag, HiOutlineKey, HiOutlineLink, HiOutlineMail, HiOutlineMap, HiOutlineMinus, HiOutlineMusicNote, HiOutlinePaperClip, HiOutlinePencilAlt, HiOutlinePhone, HiOutlinePrinter, HiOutlineQuestionMarkCircle, HiOutlineReceiptRefund, HiOutlineReply, HiOutlineSave, HiOutlineScale, HiOutlineSelector, HiOutlineSortAscending, HiOutlineSortDescending, HiOutlineSparkles, HiOutlineSpeakerphone, HiOutlineStar, HiOutlineStatusOnline, HiOutlineSupport, HiOutlineSwitchVertical, HiOutlineTable, HiOutlineTemplate, HiOutlineTerminal, HiOutlineThumbUp, HiOutlineTranslate, HiOutlineTruck, HiOutlineUpload as HiOutlineCloudUpload, HiOutlineUserCircle, HiOutlineVariable, HiOutlineVideoCamera, HiOutlineVolumeUp, HiOutlineCash, HiOutlineCreditCard, HiOutlineCurrencyDollar, HiOutlineEmojiHappy, HiOutlineEmojiSad, HiOutlineBan } from "react-icons/hi";

export type IconName = keyof typeof iconMap;

const iconMap = {
  // Feather action icons (Fi)
  edit: FiEdit,
  delete: FiTrash2,
  view: FiEye,
  add: FiPlus,
  plus: FiPlus,
  search: FiSearch,
  close: FiX,
  "user-x": FiUserX,
  refresh: FiRefreshCw,
  logout: FiLogOut,
  play: FiPlay,
  pause: FiPause,
  stop: FiSquare,
  "chevron-down": FiChevronDown,
  "chevron-up": FiChevronUp,
  "chevron-left": FiChevronLeft,
  "chevron-right": FiChevronRight,
  download: FiDownload,
  upload: FiUpload,
  file: FiFile,
  bell: FiBell,
  home: FiHome,
  users: FiUsers,
  settings: FiSettings,
  grid: FiGrid,
  calendar: FiCalendar,
  clock: FiClock,
  "alert-circle": FiAlertCircle,
  "check-circle": FiCheckCircle,
  info: FiInfo,
  star: FiStar,
  heart: FiHeart,
  share: FiShare2,
  "more-horizontal": FiMoreHorizontal,
  "arrow-up": FiArrowUp,
  "arrow-down": FiArrowDown,
  "arrow-left": FiArrowLeft,
  "arrow-right": FiArrowRight,
  "external-link": FiExternalLink,
  link: FiLink,
  mail: FiMail,
  phone: FiPhone,
  "map-pin": FiMapPin,
  user: FiUser,
  "user-plus": FiUserPlus,
  "user-check": FiUserCheck,
  "user-minus": FiUserMinus,
  person: FiUser,
  "person-add": FiUserPlus,
  "person-off": FiUserX,
  "restart-alt": FiRefreshCw,
  "arrow-forward": FiArrowRight,
  "arrow-back": FiArrowLeft,

  // Heroicons outline (HiOutline)
  "hi-home": HiOutlineHome,
  "hi-cube": HiOutlineCube,
  "hi-folder-open": HiOutlineFolderOpen,
  "hi-chart-bar": HiOutlineChartBar,
  "hi-light-bulb": HiOutlineLightBulb,
  "hi-clipboard": HiOutlineClipboardList,
  "hi-collection": HiOutlineCollection,
  "hi-academic-cap": HiOutlineAcademicCap,
  "hi-office-building": HiOutlineOfficeBuilding,
  "hi-shield-check": HiOutlineShieldCheck,
  "hi-adjustments": HiOutlineAdjustments,
  "hi-annotation": HiOutlineAnnotation,
  "hi-exclamation": HiOutlineExclamation,
  "hi-flag": HiOutlineFlag,
  "hi-globe": HiOutlineGlobe,
  "hi-inbox": HiOutlineInbox,
  "hi-library": HiOutlineLibrary,
  "hi-location-marker": HiOutlineLocationMarker,
  "hi-lock-closed": HiOutlineLockClosed,
  "hi-logout": HiOutlineLogout,
  "hi-menu": HiOutlineMenu,
  "hi-moon": HiOutlineMoon,
  "hi-pencil": HiOutlinePencil,
  "hi-photograph": HiOutlinePhotograph,
  "hi-plus": HiOutlinePlus,
  "hi-refresh": HiOutlineRefresh,
  "hi-search": HiOutlineSearch,
  "hi-sun": HiOutlineSun,
  "hi-switch-horizontal": HiOutlineSwitchHorizontal,
  "hi-tag": HiOutlineTag,
  "hi-ticket": HiOutlineTicket,
  "hi-trash": HiOutlineTrash,
  "hi-trending-up": HiOutlineTrendingUp,
  "hi-trending-down": HiOutlineTrendingDown,
  "hi-user": HiOutlineUser,
  "hi-user-add": HiOutlineUserAdd,
  "hi-user-group": HiOutlineUserGroup,
  "hi-user-remove": HiOutlineUserRemove,
  "hi-view-grid": HiOutlineViewGrid,
  "hi-view-list": HiOutlineViewList,
  "hi-x": HiOutlineX,
  "hi-zoom-in": HiOutlineZoomIn,
  "hi-zoom-out": HiOutlineZoomOut,
  "hi-cog": HiOutlineCog,
  "hi-document-report": HiOutlineDocumentReport,
  "hi-document-text": HiOutlineDocumentText,
  "hi-exclamation-circle": HiOutlineExclamationCircle,
  "hi-check-circle": HiOutlineCheckCircle,
  "hi-information-circle": HiOutlineInformationCircle,
  "hi-clock": HiOutlineClock,
  "hi-calendar": HiOutlineCalendar,
  "hi-chart-square-bar": HiOutlineChartSquareBar,
  "hi-code": HiOutlineCode,
  "hi-color-swatch": HiOutlineColorSwatch,
  "hi-database": HiOutlineDatabase,
  "hi-desktop": HiOutlineDesktopComputer,
  "hi-device-mobile": HiOutlineDeviceMobile,
  "hi-dots-horizontal": HiOutlineDotsHorizontal,
  "hi-dots-vertical": HiOutlineDotsVertical,
  "hi-download": HiOutlineDownload,
  "hi-duplicate": HiOutlineDuplicate,
  "hi-cloud-upload": HiOutlineCloudUpload,
  "hi-external-link": HiOutlineExternalLink,
  "hi-eye": HiOutlineEye,
  "hi-eye-off": HiOutlineEyeOff,
  "hi-filter": HiOutlineFilter,
  "hi-folder": HiOutlineFolder,
  "hi-gift": HiOutlineGift,
  "hi-hashtag": HiOutlineHashtag,
  "hi-key": HiOutlineKey,
  "hi-link": HiOutlineLink,
  "hi-mail": HiOutlineMail,
  "hi-map": HiOutlineMap,
  "hi-minus": HiOutlineMinus,
  "hi-music-note": HiOutlineMusicNote,
  "hi-paper-clip": HiOutlinePaperClip,
  "hi-pencil-alt": HiOutlinePencilAlt,
  "hi-phone": HiOutlinePhone,
  "hi-printer": HiOutlinePrinter,
  "hi-question-mark": HiOutlineQuestionMarkCircle,
  "hi-receipt-refund": HiOutlineReceiptRefund,
  "hi-reply": HiOutlineReply,
  "hi-save": HiOutlineSave,
  "hi-scale": HiOutlineScale,
  "hi-selector": HiOutlineSelector,
  "hi-sort-ascending": HiOutlineSortAscending,
  "hi-sort-descending": HiOutlineSortDescending,
  "hi-sparkles": HiOutlineSparkles,
  "hi-speakerphone": HiOutlineSpeakerphone,
  "hi-star": HiOutlineStar,
  "hi-status-online": HiOutlineStatusOnline,
  "hi-support": HiOutlineSupport,
  "hi-switch-vertical": HiOutlineSwitchVertical,
  "hi-table": HiOutlineTable,
  "hi-template": HiOutlineTemplate,
  "hi-terminal": HiOutlineTerminal,
  "hi-thumb-up": HiOutlineThumbUp,
  "hi-translate": HiOutlineTranslate,
  "hi-truck": HiOutlineTruck,
  "hi-user-circle": HiOutlineUserCircle,
  "hi-variable": HiOutlineVariable,
  "hi-video-camera": HiOutlineVideoCamera,
  "hi-volume-up": HiOutlineVolumeUp,
  "hi-cash": HiOutlineCash,
  "hi-credit-card": HiOutlineCreditCard,
  "hi-currency-dollar": HiOutlineCurrencyDollar,
  "hi-emoji-happy": HiOutlineEmojiHappy,
  "hi-emoji-sad": HiOutlineEmojiSad,
  "hi-ban": HiOutlineBan,

  // Additional missing material symbol aliases
  flag: HiOutlineFlag,
  lock: HiOutlineLockClosed,
  "lock-closed": HiOutlineLockClosed,
  visibility: HiOutlineEye,
  visibility_off: HiOutlineEyeOff,
  login: HiOutlineLogout,
  arrow_forward: FiArrowRight,
  arrow_back: FiArrowLeft,
  chevron_right: FiChevronRight,
  account_tree: HiOutlineCollection,
  insights: HiOutlineLightBulb,
  shield_person: HiOutlineShieldCheck,
  account_balance: HiOutlineOfficeBuilding,
  supervisor_account: HiOutlineUserCircle,
  engineering: HiOutlineCog,
  lightbulb: HiOutlineLightBulb,
  rule: HiOutlineClipboardList,
  restart_alt: FiRefreshCw,
  timer: HiOutlineClock,

  // Material Symbol name aliases (only those not already defined above)
  search_off: HiOutlineSearch,
  school: HiOutlineAcademicCap,
  people: HiOutlineUserGroup,
  group: HiOutlineUserGroup,
  groups: HiOutlineUserGroup,
  description: HiOutlineDocumentText,
  monitoring: HiOutlineChartBar,
  timeline: HiOutlineTrendingUp,
  warning: HiOutlineExclamationCircle,
  error: HiOutlineExclamationCircle,
  speed: HiOutlineLightBulb,
  psychology: HiOutlineLightBulb,
  auto_awesome: HiOutlineSparkles,
  rocket_launch: HiOutlineLightBulb,
  task_alt: HiOutlineCheckCircle,
  calendar_today: HiOutlineCalendar,
  folder_open: HiOutlineFolderOpen,
  track_changes: HiOutlineAdjustments,
  person_search: HiOutlineSearch,
  hub: HiOutlineCollection,
  expand_more: FiChevronDown,
  remove: HiOutlineMinus,
  bolt: HiOutlineLightBulb,
  badge: HiOutlineShieldCheck,
  unfold_more: HiOutlineSwitchVertical,
  work: HiOutlineCube,
  schedule: HiOutlineClock,
  person_add: HiOutlineUserAdd,
  emergency: HiOutlineExclamationCircle,
  linkedin: HiOutlineLink,
  verified_user: HiOutlineShieldCheck,
  location_on: HiOutlineLocationMarker,
  check_circle: HiOutlineCheckCircle,
  open_in_new: HiOutlineExternalLink,
  cake: HiOutlineGift,
  touch_app: HiOutlineSelector,
  person_off: HiOutlineUserRemove,
  analytics: HiOutlineChartBar,
  checklist: HiOutlineClipboardList,
  layers: HiOutlineCollection,
  priority_high: HiOutlineExclamation,
  trending_up: HiOutlineTrendingUp,
  trending_down: HiOutlineTrendingDown,
  sentiment_satisfied: HiOutlineEmojiHappy,
};

interface IconProps {
  name: string;
  size?: number;
  className?: string;
}

export function Icon({ name, size = 18, className = "" }: IconProps) {
  const Component = iconMap[name as keyof typeof iconMap];
  if (!Component) {
    console.warn(`Icon "${name}" not found in icon map`);
    return null;
  }
  return <Component size={size} className={className} />;
}

export { iconMap };
export type { IconProps };
